id: rails-db-config

info:
  name: Ruby-on-Rails Database Configuration Exposure
  author: pdteam,geeknik
  severity: low
  tags: config,exposure,rails

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config/db.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "adapter:"
          - "db:"
          - "production:"
        condition: and
        part: body

      - type: status
        status:
          - 200